basePath: /api/v1
definitions:
  golang-crud-gin_pkg_brand_data_response.Response:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
  golang-crud-gin_pkg_sku_data_response.Response:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
host: localhost:8888
info:
  contact: {}
  description: A Brand service API in Go using Gin framework
  title: Brand Service API
  version: "1.0"
paths:
  /brand:
    get:
      description: Return list of brand.
      responses:
        "200":
          description: OK
          schema:
            type: obejct
      summary: Get All brand.
  /brand/{brandId}:
    get:
      description: Return the tahs whoes brandId valu mathes id.
      parameters:
      - description: update brand by id
        in: path
        name: brandId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/golang-crud-gin_pkg_brand_data_response.Response'
      summary: Get Single brand by id.
  /sku/{skuId}:
    get:
      description: Return the tahs whoes skuId valu mathes id.
      parameters:
      - description: update sku by id
        in: path
        name: skuId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/golang-crud-gin_pkg_sku_data_response.Response'
      summary: Get Single sku by id.
swagger: "2.0"
